/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Request;

import EHView123.EHView;
import EventLoginPage123.EloginPage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARFAH
 */
public class Req extends javax.swing.JFrame {

    /**
     * Creates new form Req
     */
    public Req() {
        initComponents();
           show_user();
    }

public ArrayList<Userreq> userList() {
    ArrayList<Userreq> userList = new ArrayList<>();
    
     try
               {
                  
               //    EIDL.setText(EventLoginPage123.EloginPage.EventIDTF.getText()+" -");
                   // EventNameL.setText(EventLoginPage123.EloginPage.EventIDTF.getText());
                   // Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/MiniProject","postgres","*************");
 
                   String ql="Select student_table.*,request_table.money_given from student_table inner join request_table on student_table.prn=request_table.prn and '"+EloginPage.EventIDTF.getText()+"'=request_table.event_id";
                          
                    // JOptionPane.showMessageDialog(null,  sql );
System.out.println(ql);
  //JOptionPane.showMessageDialog(null, "IN");
 //JOptionPane.showMessageDialog(null,  EloginPage.EventIDTF.getText() );
                    Statement ps =con.createStatement();
                    ResultSet rs = ps.executeQuery(ql);
                   Userreq user;
                   while(rs.next()) {
                        user=new Userreq(rs.getString("prn" ),rs.getString("name" ),rs.getString("phone_number" ),rs.getString("e_mail" ),rs.getString("branch" ),rs.getString("year" ),rs.getString("money_given" ));
                        userList.add(user);  
                        //JOptionPane.showMessageDialog(null, "IN TRY");
                   }
               }
 catch(Exception e) {
               JOptionPane.showMessageDialog(null, e);
         }
         return userList;
    }
   
    public void show_user() {
    ArrayList<Userreq> list = userList();
        DefaultTableModel model= (DefaultTableModel) ReqTable.getModel();
        Object [] row = new Object[8];
    for(int i=0;i<list.size();i++){
     row[0]=i+1;   
row[1]=list.get(i).getprn();
        row[2]=list.get(i).getname();
        row[3]=list.get(i).getphone_number();
        row[4]=list.get(i).gete_mail();
        row[5]=list.get(i).getbranch();
        row[6]=list.get(i).getyear();
          row[7]=list.get(i).getmoney_given();

        model.addRow(row);
    }
    /*   DefaultTableModel mode=(DefaultTableModel) ReqTable.getModel();
         mode.setRowCount(0);
         show_user();*/
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReqTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S. No.", "PRN", "Name", "Phone", "E-mail", "Branch", "Year", "Money Given"
            }
        ));
        ReqTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReqTableMouseClicked(evt);
            }
        });
        ReqTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ReqTableInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ReqTable);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReqTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReqTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ReqTableMouseClicked

    private void ReqTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ReqTableInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ReqTableInputMethodTextChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                try
      {
       EHView menu= new EHView();
                        menu.setVisible(true);
                        setVisible(false);
                         //  EIT.setText(EventLoginPage123.EloginPage.EventIDTF.getText());
      }
      catch(Exception e) {
               JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Req.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Req.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Req.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Req.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Req().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable ReqTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
