/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatatoJtable;


import EHRegistration.EHReg;
import EventListTable.EList;
import GroupMembers.GroupMembPage;
import LogOutPage.LogOut;
import OriginalStudentLoginPage.OStudentLoginPage;
import StudentUpdateForm.SUForm;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ARFAH
 */
public class StudentView extends javax.swing.JFrame {
String filename=null;
byte[] poster=null;
    /**
     * Creates new form StudentView
     */
    public StudentView() {
        initComponents();
        show_user();
    }
public ArrayList<User> userList() {
    ArrayList<User> userList = new ArrayList<>();
    try
               {
                   // Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/MiniProject","postgres","**************");
 
                   String sql="Select et.event_id,et.event_name,et.venue,et.edate,et.contact,et.email,et.duration, et.endtime, et.charge,rt.money_given,et.activity,et.poster \n" +
"from event_table et INNER JOIN register_table rt\n" +
"ON et.event_id=rt.event_id\n" +
"and '"  +  OStudentLoginPage.PRNT.getText() + "' = rt.prn;";
                         
                     //JOptionPane.showMessageDialog(null,  sql );
System.out.println(sql);
                   //JOptionPane.showMessageDialog(null,  OStudentLoginPage.PRNT.getText() );
                    Statement ps =con.createStatement();
                           
                    ResultSet rs = ps.executeQuery(sql);
                    User user;
                    while(rs.next()) {
                        user=new User(rs.getString("event_id" ),rs.getString("event_name" ),rs.getString("venue" ),rs.getString("edate" ),rs.getString("contact" ),rs.getString("email" ),rs.getString("duration" ),rs.getString("endtime" ),rs.getString("charge" ),rs.getString("money_given" ),rs.getString("activity" ), rs.getBytes("poster"));
                        userList.add(user);
                    }
               }
      catch(Exception e) {
               JOptionPane.showMessageDialog(null, e);
         }
    return userList;
}
public void show_user() {
    ArrayList<User> list = userList();
    DefaultTableModel model= (DefaultTableModel) StudentTable.getModel();
    Object [] row = new Object[12];
    for(int i=0;i<list.size();i++){
        row[0]=i+1;
        row[1]=list.get(i).getevent_id();
        row[2]=list.get(i).getevent_name();
        row[3]=list.get(i).getvenue();
        row[4]=list.get(i).getedate();
        row[5]=list.get(i).getcontact();
        row[6]=list.get(i).getemail();
        row[7]=list.get(i).getduration();
        row[8]=list.get(i).getendtime();
          row[9]=list.get(i).getcharge();
          row[10]=list.get(i).getmoney_given();
          row[11]=list.get(i).getactivity();
        model.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        UpdateB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ListEB = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PosterL = new javax.swing.JLabel();
        GMB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        LogoutB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpdateB.setText("Update Info");
        UpdateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel2.setText("Here's a list of the events you've taken part in");

        ListEB.setText("List of events this year");
        ListEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListEBActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        PosterL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PosterL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PosterL, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );

        GMB.setText("Group Members");
        GMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GMBActionPerformed(evt);
            }
        });

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S. No.", "Event Id", "Event Name", "Venue", "Date", "Contact", "Email", "Duration", "End Time", "Charge", "Amount Paid", "Active?"
            }
        ));
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudentTable);

        LogoutB.setText("Log Out");
        LogoutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(348, 348, 348)
                        .addComponent(ListEB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(UpdateB)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(GMB)
                        .addGap(35, 35, 35)
                        .addComponent(LogoutB)))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UpdateB)
                    .addComponent(LogoutB)
                    .addComponent(GMB))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListEB)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBActionPerformed
        // TODO add your handling code here:
           try
        {
           SUForm  menu= new SUForm();
            menu.setVisible(true);
            setVisible(false);
            SUForm.PRNT.setText(OStudentLoginPage.PRNT.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_UpdateBActionPerformed

    private void ListEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListEBActionPerformed
        // TODO add your handling code here:
         try
        {
           EList  menu= new EList();
            menu.setVisible(true);
            setVisible(false);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ListEBActionPerformed

    private void LogoutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBActionPerformed
        // TODO add your handling code here:
        try
        {
           LogOut menu= new LogOut();
            menu.setVisible(true);
            setVisible(false);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_LogoutBActionPerformed

    private void GMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GMBActionPerformed
        // TODO add your handling code here:
          GroupMembPage menu= new GroupMembPage();
                        menu.setVisible(true);
                        setVisible(false);
    }//GEN-LAST:event_GMBActionPerformed

    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        // TODO add your handling code here:
        int i= StudentTable.getSelectedRow();
        TableModel model = StudentTable.getModel();
        byte[] img = (userList().get(i).getImage());
         ImageIcon imageIcon=new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(PosterL.getWidth(), PosterL.getHeight(), Image.SCALE_SMOOTH));
        PosterL.setIcon(imageIcon);
    }//GEN-LAST:event_StudentTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GMB;
    private javax.swing.JButton ListEB;
    private javax.swing.JButton LogoutB;
    private javax.swing.JLabel PosterL;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton UpdateB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
