/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EventLoginPage123;

import EHView123.EHView;
import static EHView123.EHView.EL;
import MainPage.MainPageView;
import NewPassword.NewPassForm;
import Verification.VeriForm;
import eventloginpage.EventLoginPageNew;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ARFAH
 */
public class EloginPage extends javax.swing.JFrame {
public static String  event= "";
    /**
     * Creates new form EloginPage
     */
    public EloginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FPassLabel = new javax.swing.JLabel();
        LoginB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LoginTF = new javax.swing.JTextField();
        BackB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EventIDTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PassTF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FPassLabel.setText("Forgot Password?");
        FPassLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FPassLabelMouseMoved(evt);
            }
        });
        FPassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FPassLabelMousePressed(evt);
            }
        });

        LoginB.setText("Login");
        LoginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBActionPerformed(evt);
            }
        });

        jLabel1.setText("Login Id");

        LoginTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTFActionPerformed(evt);
            }
        });

        BackB.setText("Back");
        BackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBActionPerformed(evt);
            }
        });

        jLabel3.setText("Event ID");

        jLabel2.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LoginTF, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(PassTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EventIDTF, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(BackB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LoginB, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(FPassLabel)
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoginTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(EventIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(FPassLabel)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBActionPerformed
      
        try
               {
                     
                   //System.out.println(EloginPage.EventIDTF.getText().toString());

                   // Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/MiniProject","postgres","*********");
                    String sql="Select * from event_login where login_id=? and password=? and event_id=?";
                  
System.out.println(EloginPage.EventIDTF.getText());
                    
                  PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, LoginTF.getText());
                                        ps.setString(2, PassTF.getText());
                                                            ps.setString(3, EventIDTF.getText());
 ResultSet rs = ps.executeQuery();
                    if(rs.next())
                    {

                        JOptionPane.showMessageDialog(null, "LoginId and Password match");
                        EHView menu= new EHView();
                        menu.setVisible(true);
                        setVisible(false);
                           
                    }
                    else
                    {
                           JOptionPane.showMessageDialog(null, "LoginId and Password does not match");
           LoginTF.setText("");
          PassTF.setText("");
          EventIDTF.setText("");
                    }
                    
                  
               }
                  catch(Exception e) {
               JOptionPane.showMessageDialog(null, e);
         }
              
    }//GEN-LAST:event_LoginBActionPerformed

    private void BackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBActionPerformed
        // TODO add your handling code here:
        try
      {
       MainPageView menu= new MainPageView();
                        menu.setVisible(true);
                        setVisible(false);
      }
      catch(Exception e) {
               JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_BackBActionPerformed

    private void LoginTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginTFActionPerformed

    private void FPassLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FPassLabelMouseMoved
        // TODO add your handling code here:
        FPassLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_FPassLabelMouseMoved

    private void FPassLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FPassLabelMousePressed
        // TODO add your handling code here:
       if(EventIDTF.getText().equals("")||LoginTF.getText().equals(""))
        {
             JOptionPane.showMessageDialog(null, "Please enter your event_id and login_id");
        }
        else
        {
               //JOptionPane.showMessageDialog(null, "In else");
                   try
      {     Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/MiniProject","postgres","**********");
               String q="Select event_id from event_login where login_id='" +EloginPage.LoginTF.getText()+"'";
               //JOptionPane.showMessageDialog(null, q);
            PreparedStatement ps = con.prepareStatement(q);
           
               ResultSet rs = ps.executeQuery();              
              // JOptionPane.showMessageDialog(null, "'"+rs+"'");
              
//User user;
                   while(rs.next()) {
                        //user=new User(rs.getString("event_id" ));
                        String eid=rs.getString("event_id");
                                
            if(EventIDTF.getText().equals(eid))
            {
         try
      {
      /*NewPassForm menu= new NewPassForm();
                        menu.setVisible(true);
                        setVisible(false);*/
          VeriForm menu= new VeriForm();
                        menu.setVisible(true);
                        setVisible(false);
      }
      catch(Exception e) {
               JOptionPane.showMessageDialog(null, e);
         }
           }
      }
      }
                 
           catch(Exception e) {
               JOptionPane.showMessageDialog(null, "Hello");
         }
        
        }
    }//GEN-LAST:event_FPassLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EloginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EloginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EloginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EloginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EloginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackB;
    public static javax.swing.JTextField EventIDTF;
    private javax.swing.JLabel FPassLabel;
    private javax.swing.JButton LoginB;
    public static javax.swing.JTextField LoginTF;
    public static javax.swing.JPasswordField PassTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
