/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EHUpdateForm;

import static EHRegistration.EHReg.PosterL;
import EHView123.EHView;
import EventLoginPage123.EloginPage;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ARFAH
 */
public class EHUForm extends javax.swing.JFrame {
String filename=null;
byte[] poster=null;
    /**
     * Creates new form EHUForm
     */
    public EHUForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EIT = new javax.swing.JTextField();
        EnameT = new javax.swing.JTextField();
        VenueT = new javax.swing.JTextField();
        ChargeT = new javax.swing.JTextField();
        NumberT = new javax.swing.JTextField();
        EMT = new javax.swing.JTextField();
        DurationT = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        UpdateB = new javax.swing.JButton();
        BackB = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PasswordT = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        EndtimeT = new javax.swing.JTextField();
        DelEventB = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ActiveB = new javax.swing.JButton();
        ActivityTF = new javax.swing.JTextField();
        EPosterB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PosterL = new javax.swing.JLabel();
        eDateT = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 25)); // NOI18N
        jLabel1.setText("Update your details here");

        jLabel2.setText("Please enter your event-id:");

        jLabel3.setText("Event Name:");

        jLabel4.setText("Venue:");

        jLabel5.setText("Date of Event:");

        jLabel6.setText("Charge of the event:");

        jLabel7.setText("Contact Number:");

        jLabel8.setText("E-mail:");

        jLabel9.setText("Duration of Event:");

        EIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EITActionPerformed(evt);
            }
        });
        EIT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EITKeyReleased(evt);
            }
        });

        UpdateB.setText("Update");
        UpdateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBActionPerformed(evt);
            }
        });

        BackB.setText("Back");
        BackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBActionPerformed(evt);
            }
        });

        jLabel11.setText("What's your Password?");

        jLabel12.setText("Do you want to deactivate your event?");

        jLabel15.setText("Activity:");

        PasswordT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordTKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BackB)
                        .addGap(124, 124, 124)
                        .addComponent(UpdateB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(82, 82, 82))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PasswordT)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(PasswordT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackB)
                    .addComponent(UpdateB))
                .addGap(72, 72, 72)
                .addComponent(jLabel15)
                .addGap(63, 63, 63)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Endtime of Event:");

        DelEventB.setText("Deactivate Event");
        DelEventB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelEventBActionPerformed(evt);
            }
        });

        jLabel13.setText("Do you want to restart your event?");

        ActiveB.setText("Reactivate Event");
        ActiveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActiveBActionPerformed(evt);
            }
        });

        EPosterB.setText("Choose New Event Poster");
        EPosterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPosterBActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        PosterL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PosterL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PosterL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        eDateT.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EPosterB)
                .addGap(112, 112, 112)
                .addComponent(DelEventB)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 541, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(eDateT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205)
                                .addComponent(ActivityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EIT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(766, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EndtimeT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VenueT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(EnameT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ActiveB)
                        .addGap(149, 149, 149))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addComponent(jLabel1))
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(149, 149, 149)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(DurationT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(EMT, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NumberT, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ChargeT, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(64, 64, 64)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EnameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(VenueT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(ActivityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(eDateT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DelEventB)
                    .addComponent(EPosterB))
                .addGap(32, 32, 32)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EndtimeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ActiveB)))
                .addGap(56, 56, 56))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(DurationT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel1)
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel2)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel3)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel4)
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel5)
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(ChargeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(NumberT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(EMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel9)))
                            .addGap(119, 119, 119))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap()))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBActionPerformed
        // TODO add your handling code here:
        if(EIT.getText().equals("")||EnameT.getText().equals("")||VenueT.getText().equals("")||eDateT.getDate().equals("")||ChargeT.getText().equals("")||NumberT.getText().equals("")||EMT.getText().equals("") ||DurationT.getText().equals("") ||EndtimeT.getText().equals("") ||PasswordT.getText().equals("")||PasswordT.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please enter all the data");
        }
        else
        {   
        try
        {
            // Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/MiniProject","postgres","*************");
              /* String query2="Select password from event_login where event_id='" +EHUForm.EIT.getText()+  "'";
            PreparedStatement ps2 = con.prepareStatement(query2);
            ps2.executeUpdate();
            if(EHUForm.PasswordT.getText() !=query2 )*/
                 /*JOptionPane.showMessageDialog(null, " '"+EHUForm.PasswordT.getText()+"'");
                 JOptionPane.showMessageDialog(null,  " '"+EventLoginPage123.EloginPage.PassTF.getText() +"'" );
                 String m=EHUForm.PasswordT.getText();
                 String n=EventLoginPage123.EloginPage.PassTF.getText();*/
            if( EHUForm.PasswordT.getText().equals(EventLoginPage123.EloginPage.PassTF.getText()) )
            {
                String query="update event_table set event_name=?,venue=?, edate=?,charge=?,contact=?,email=?,duration=? ,endtime=? , poster=? where event_id  IN(Select event_id from event_login where event_id='" +EHUForm.EIT.getText()+"' and password='" +EHUForm.PasswordT.getText()+"')";
                PreparedStatement ps = con.prepareStatement(query);
           
                ps.setString(1, EnameT.getText());
                ps.setString(2, VenueT.getText());
                 ps.setString(3, ((JTextField) eDateT.getDateEditor().getUiComponent()).getText());
               // ps.setString(3, eDateT.getDateFormatString());
                ps.setString(4, ChargeT.getText());
                ps.setString(5, NumberT.getText());
                ps.setString(6, EMT.getText());
                ps.setString(7, DurationT.getText());
                ps.setString(8, EndtimeT.getText());
                ps.setBytes(9, poster);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "You have successfully updated your data.");
                /*String query1="update event_login set password=? where event_id IN('"+EHUForm.EIT.getText()+"')";
                PreparedStatement ps1 = con.prepareStatement(query1);
                ps1.setString(1, PasswordT.getText());
                ps1.executeUpdate();
                JOptionPane.showMessageDialog(null, "You have successfully updated your data.");*/
             
            }
            else
            {
               JOptionPane.showMessageDialog(null, "Wrong Password. No update occurred");
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_UpdateBActionPerformed

    private void BackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBActionPerformed
        // TODO add your handling code here:
        try
        {
            EHView menu= new EHView();
            menu.setVisible(true);
            setVisible(false);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BackBActionPerformed

    private void EITKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EITKeyReleased
        // TODO add your handling code here:
 abc();
    }//GEN-LAST:event_EITKeyReleased

    private void EITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EITActionPerformed
        // TODO add your handling code here:
      abc();
    }//GEN-LAST:event_EITActionPerformed

    private void DelEventBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelEventBActionPerformed
        // TODO add your handling code here:
         int opt= JOptionPane.showConfirmDialog(null, "Are you sure you want to deactivate your event?", "Delete", JOptionPane.YES_NO_OPTION);
        if(opt==0)
        {
                 if( EHUForm.PasswordT.getText().equals(EventLoginPage123.EloginPage.PassTF.getText()) )
            {
                try
               {
                   // Class.forName("oracle.jdbc.driver.OracleDriver");
                  // System.out.println("In try" );
                    Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/MiniProject","postgres","************");
//System.out.println("Connected");
                   // EloginPage.event  = EloginPage.EventIDTF.getText();
                      
System.out.println(EloginPage.EventIDTF.getText());

String query="update event_table set activity='INACTIVE' where event_id= '"+EloginPage.EventIDTF.getText()+"'";
                PreparedStatement ps = con.prepareStatement(query);
                                     //JOptionPane.showMessageDialog(null,  query );

                    JOptionPane.showMessageDialog(null,  "Event Deactivated");
 ps.executeUpdate();
        }
                  catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
                  else
            {
               JOptionPane.showMessageDialog(null, "Wrong Password. Event still ACTIVE.");
            }
        }
    }//GEN-LAST:event_DelEventBActionPerformed

    private void ActiveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActiveBActionPerformed
        // TODO add your handling code here:
         if( EHUForm.PasswordT.getText().equals(EventLoginPage123.EloginPage.PassTF.getText()) )
            {
        try
        {
            // Class.forName("oracle.jdbc.driver.OracleDriver");
            // System.out.println("In try" );
            Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/MiniProject","postgres","***********");
            //System.out.println("Connected");
            // EloginPage.event  = EloginPage.EventIDTF.getText();

            System.out.println(EloginPage.EventIDTF.getText());

            String query="update event_table set activity='ACTIVE' where event_id= '"+EloginPage.EventIDTF.getText()+"'";
            PreparedStatement ps = con.prepareStatement(query);
            //JOptionPane.showMessageDialog(null,  query );

            JOptionPane.showMessageDialog(null,  "Event successfully reactivated.");
            ps.executeUpdate();
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            }
           else
            {
               JOptionPane.showMessageDialog(null, "Wrong Password.");
            }

    }//GEN-LAST:event_ActiveBActionPerformed

    private void EPosterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPosterBActionPerformed
        // TODO add your handling code here:
       JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        ImageIcon imageIcon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(PosterL.getWidth(), PosterL.getHeight(), Image.SCALE_SMOOTH));
        PosterL.setIcon(imageIcon);
        try
        {
            File image = new File(filename);
            FileInputStream fis =  new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum = fis.read(buf))!= -1; )
            {
                bos.write(buf, 0, readNum);
            }
            poster=bos.toByteArray();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_EPosterBActionPerformed

    private void PasswordTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordTKeyReleased
        // TODO add your handling code here:
                     try
        {
                    Connection con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/MiniProject","postgres","*********");
                    String sql="Select et.* from event_table et INNER JOIN event_login el ON el.event_id = et.event_id where et.event_id=? and el.password=?";
                                PreparedStatement s = con.prepareStatement(sql);
                            s.setString(1, EIT.getText());
                              s.setString(2, PasswordT.getText());
                            ResultSet rs=s.executeQuery();
                            if(rs.next())
                            {
                                String ename=rs.getString("event_name");
                                EnameT.setText(ename);
                                 String venue=rs.getString("venue");
                                VenueT.setText(venue);
                                 String edate=rs.getString("edate");
                                ((JTextField)eDateT.getDateEditor().getUiComponent()).setText(edate);
                                 String charge=rs.getString("charge");
                                ChargeT.setText(charge);
                                 String contact=rs.getString("contact");
                                NumberT.setText(contact);
                                 String email=rs.getString("email");
                                EMT.setText(email);
                                 String duration=rs.getString("duration");
                                DurationT.setText(duration);
                                 String endtime=rs.getString("endtime");
                                EndtimeT.setText(endtime);
                                 String activity=rs.getString("activity");
                                ActivityTF.setText(activity);
                            }

        }
                    catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Event_id - Password mismatch!");
        }
                                        

    }//GEN-LAST:event_PasswordTKeyReleased

    private void abc()
    {
         JOptionPane.showMessageDialog(null, "Please don't change the text.");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EHUForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EHUForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EHUForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EHUForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EHUForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActiveB;
    private javax.swing.JTextField ActivityTF;
    private javax.swing.JButton BackB;
    private javax.swing.JTextField ChargeT;
    private javax.swing.JButton DelEventB;
    private javax.swing.JTextField DurationT;
    public static javax.swing.JTextField EIT;
    private javax.swing.JTextField EMT;
    private javax.swing.JButton EPosterB;
    private javax.swing.JTextField EnameT;
    private javax.swing.JTextField EndtimeT;
    private javax.swing.JTextField NumberT;
    public static javax.swing.JPasswordField PasswordT;
    private javax.swing.JLabel PosterL;
    private javax.swing.JButton UpdateB;
    private javax.swing.JTextField VenueT;
    private com.toedter.calendar.JDateChooser eDateT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
